### PR TITLE
Refactor height RGBD

### PR DESCRIPTION
**Pull request by markus-hinsche**
Changes: 
- sort import
- polish imports to fit code on less lines
- Add whitespace to semantically structure into code blocks

### CODE REVIEW

**Review by prashant905 — APPROVED** [review]
LGTM!

**Comment by markus-hinsche** [comment]
We will wait with merging for https://dev.azure.com/cgmorg/ChildGrowthMonitor/_workitems/edit/1772 to finish

**Comment by markus-hinsche** [comment]
https://dev.azure.com/cgmorg/ChildGrowthMonitor/_workitems/edit/1772 was never finished, so I suggest to go ahead and merge this

**Review by gangooteli — APPROVED** [review]
LGTM

**Pull request merged**
